### ISSUE TITLE
pytorch code

### ISSUE THREAD

**Issue by YCJGG** [lightaime/deep_gcns_torch#1]
Can you kindly share your pytorch  code? 
I don't mind the draft version:)
This is my email:
jgg_jingyizhang@foxmail.com

**Comment by guochengqian** [comment]
@YCJGG Hello, thanks for your interest in our work. The draft of Pytorch version Deep GCN is ready now. Please check our [https://github.com/lightaime/deep_gcns_torch](repo) and feel free to ask any question.
