### ISSUE TITLE
Model cannot converge problem

### ISSUE THREAD

**Issue by im-wll** [lightaime/deep_gcns_torch#10]
Your work is very interesting.  I use the network structure which introduced in your paper on the database of image classification.  But I find that as the gcn network goes deeper, even use the Residual Connections of gcn , Convergence of networks get worse.  when the depth of network is 2, the accuracy of train set can reach 80%, but when the depth of network grows to 7, the accuracy only drop to 50%. Is there also the problem of gradient disappearing?

**Comment by lightaime** [comment]
We haven't tried try to apply DeepGCNs to image yet. So not sure about the problem. But which is the gcn operator you used?

**Comment by im-wll** [comment]
I use the edgeConv,MRconv ,both of them have the problem

**Comment by lightaime** [comment]
You can try to combine CNN with GCN. I think using GCN solely for image classification is not a ideal choice.

**Comment by im-wll** [comment]
thank you for your advice.  In fact, that's what I did. I first use the `resnet18` to extract feature, then I input the feature to GCN net. But when I use your code to construct graph network, the network cann't convert even I train many epoches.

**Comment by lightaime** [comment]
Maybe  you can try to Concat the resnet18 features at the end of your
network.
