### ISSUE TITLE
怎么让NeighborSampler 和deepgcn配合使用 ???

### ISSUE THREAD

**Issue by zsz00** [lightaime/deep_gcns_torch#14]
怎么让 torch_geometric.data.NeighborSampler 和deepgcn配合使用 ???

用自己数据 和 sage 时, 需要用NeighborSampler 来加载数据, 怎么才能和deepgcn 配合使用??
尝试了一些没成功..  
你们给个示例吗?  基于Reddit数据的节点分类就行.

**Comment by lightaime** [comment]
Thanks for your suggestion. I am quite busy with ECCV these days. I would like to provide some samples to use torch_geometric.data.NeighborSampler with DeepGCNs after ECCV.
