### ISSUE TITLE
Cannot run GAT with multiple heads attention on PPI

### ISSUE THREAD

**Issue by mingloo** [lightaime/deep_gcns_torch#15]
When running the following commands on `PPI` dataset, it will crash eventually.

`python -u examples/ppi/main.py --phase train --conv gat --data_dir /data/deepgcn/ppi  --block dense --n_filters 256 --n_heads 4 `

@lightaime @guochengqian

**Comment by guochengqian** [comment]
> When running the following commands on `PPI` dataset, it will crash eventually.
> 
> `python -u examples/ppi/main.py --phase train --conv gat --data_dir /data/deepgcn/ppi --block dense --n_filters 256 --n_heads 4 `
> 
> @lightaime @guochengqian

Hi @mingloo. GAT is not the main focus of our work. For now,  our code only supports GAT with one head by default (used in our experiment). Sorry for the inconvenience.

**Comment by mingloo** [comment]
Understand. 

Closed this now.
