### ISSUE TITLE
Latest versions of torch-sparse and torch-scatter are incompatible with pytorch 1.2

### ISSUE THREAD

**Issue by peihaowang** [lightaime/deep_gcns_torch#16]
Running `source deepgcn_env_install.sh` to set up the local environment will report the error messages while building wheels of torch-sparse and torch-scatter as below:

```
/tmp/pip-install-bhreqzix/torch-scatter/csrc/segment_csr.cpp:43:24: error: ‘torch::autograd::AutogradContext’ has not been declared
   using torch::autograd::AutogradContext;
```

The official repository told me that the latest version requires pytorch 1.4 at least. However, the `deepgcn_env_install.sh` specifies `pytorch=1.2`. I fixed this issue by upgrading to pytorch 1.4 and reinstalling all of the extension libraries.

I'd suggest fixing the `deepgcn_env_install.sh` script by specifying 1.4 version of pytorch.

My two cents. Thanks.

**Comment by lightaime** [comment]
Thanks for your fix @peihaowang very much. I have updated the `deepgcn_env_install.sh`.
