### ISSUE TITLE
torch_sparse  version problem

### ISSUE THREAD

**Issue by quqxui** [lightaime/deep_gcns_torch#18]
RuntimeError: Detected that PyTorch and torch_sparse were compiled with different CUDA versions. PyTorch has CUDA version 10.1 and torch_sparse has CUDA version 10.0. Please reinstall the torch_sparse that matches your PyTorch install.

**Comment by lightaime** [comment]
Hi @quqxui . You need to install them with the same version of CUDA. Can you try to install PyTorch with CUDA version 10.0 by using `source deepgcn_env_install.sh`

**Comment by quqxui** [comment]
Thank you! But I have one more question, i can't figure out  where are you code about the plainGCN, and which line can implement the short connection.  Thank your response very much !

**Comment by guochengqian** [comment]
> Thank you! But I have one more question, i can't figure out where are you code about the plainGCN, and which line can implement the short connection. Thank your response very much !

Remove the residual connection inside ResDynBlock is the PlainGCN block we use. We will add the plain GCN block in one week.

**Comment by guochengqian** [comment]
Hi. PlainGCN has been added to this Pytorch repo. please check file `https://github.com/lightaime/deep_gcns_torch/blob/master/gcn_lib/dense/torch_vertex.py` Line 74

**Comment by guochengqian** [comment]
> RuntimeError: Detected that PyTorch and torch_sparse were compiled with different CUDA versions. PyTorch has CUDA version 10.1 and torch_sparse has CUDA version 10.0. Please reinstall the torch_sparse that matches your PyTorch install.

Hi. You can check our script for the PyG installation. We also recommend you to refer to its official document. https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html
