### ISSUE TITLE
My training is very slow

### ISSUE THREAD

**Issue by linhaojia13** [lightaime/deep_gcns_torch#20]
Hi, I trained the sem_seg_sparse model using 2 Tesla V100 GPUs, however, I found the training is very very slow and it takes several minutes to forward a batch! Just a batch! The training is under the default configuration. I had checked the GPU situation and found it is working. Do you have any idea about this?

**Comment by lightaime** [comment]
Hi, it is very slow if you use the spare version since pytorch geometric
dose not optimize for knn graph. I suggest you to use the sem_seg_dense
which uses a dense data format and the gcns are implemented with the native
pytorch.

**Comment by linhaojia13** [comment]
Hi, Thank you for your prompt reply. I follow your advice to use the dense version but it comes the same problem as I trained the sparse one.

**Comment by lightaime** [comment]
The dense version should be faster but it is still slow since the network
is very deep. To further accelerate the training, you can use 14 layers
instead of 28 layers, use mrconv instead of edgeconv by setting "--conv
mr", use smaller knn by setting '--kernel_size' smaller... Or you can try
the ppi experiment which uses a smaller dataset.

**Comment by linhaojia13** [comment]
Thank you for you advice, now I realize that deep_gcns_torch may be not a friendly repo to me and my GPUs ...hhhhh
By the way, is there a gap on time efficiency between the tensorflow version and  pytorch version of DeepGCNs ?

**Comment by lightaime** [comment]
The tensorflow version is faster. But it still takes about two days to
finish 100 epochs.

**Comment by linhaojia13** [comment]
Thank you very much.

**Comment by mingloo** [comment]
Hi @lightaime 

I've found there are 2 ways for sparse KNN neighborhood calculation when running `seg_sem_sparse`: `knn_graph_matrix` and `knn_graph`.  

The `knn_graph_matrix` is based on pairwise distance matrix but it assumes the input have same number of nodes in each graph (batch mode). However, the `knn_graph` is coming from `torch_cluster` and can support different number of nodes in each graph (batch mode).

Please correct me if there is anything wrong or missed.
