### ISSUE TITLE
visualization 

### ISSUE THREAD

**Issue by quqxui** [lightaime/deep_gcns_torch#21]
Hi, Could you please tell me how you visualize the S3DIS dataset? 
 I can't find the toolkit about  `from TorchTools.DataTools import indoor3d_util`

**Comment by lightaime** [comment]
In our paper, we visualize point clouds based on the tensorflow implementation (See [https://github.com/lightaime/deep_gcns/blob/master/sem_seg/visualization.ipynb](https://github.com/lightaime/deep_gcns/blob/master/sem_seg/visualization.ipynb) ). You can adapt it for the pytorch version. It would take much time. We also provide a visualization for partnet on this pytorch version. You can check here https://github.com/lightaime/deep_gcns_torch/blob/master/examples/part_sem_seg/visualize.py.
