### ISSUE TITLE
Can deep_gcn take point cloud repressed by 3d coordinate only?

### ISSUE THREAD

**Issue by MCLYang** [lightaime/deep_gcns_torch#22]
I went through your paper and code and found each point has more than 3 features. However, could I take each point with xyz only and NOT including rest features like surface normal and color? Appreciate if you can provide more instruction how could I adjust the number of input channel. Thank you

**Comment by lightaime** [comment]
Sure you can. You can simply set the input channels as 3 by `--in_channels 3`. See https://github.com/lightaime/deep_gcns_torch/blob/da2bdd699a0e6553e6a1246ce0f81e4cc0faf82f/examples/sem_seg_dense/opt.py#L24 and https://github.com/lightaime/deep_gcns_torch/blob/da2bdd699a0e6553e6a1246ce0f81e4cc0faf82f/examples/sem_seg_dense/architecture.py#L21.

**Comment by MCLYang** [comment]
> Sure you can. You can simply set the input channels as 3 by `--in_channels 3`. See
> 
> https://github.com/lightaime/deep_gcns_torch/blob/da2bdd699a0e6553e6a1246ce0f81e4cc0faf82f/examples/sem_seg_dense/opt.py#L24
> 
> and
> https://github.com/lightaime/deep_gcns_torch/blob/da2bdd699a0e6553e6a1246ce0f81e4cc0faf82f/examples/sem_seg_dense/architecture.py#L21
> 
> .

Thank you for the quick response. Please stay safe recently :)

**Comment by lightaime** [comment]
Thanks. Stay safe!
