### ISSUE TITLE
GPU's capacity

### ISSUE THREAD

**Issue by MCLYang** [lightaime/deep_gcns_torch#23]
I am training DGCN by my own dataset. Unlike S3DIS, my data looks like N * 20000 * 6, which means that each frame has 20000 points. I try to load it on my 2 GTX 1080Ti but I cannot even load 1 batch on one GPU. My question is : "Do you think Nvidia V100 can load my data for sure?" If you don't think V100 cannot load it neither, would you recommend that I down sample my dataset?

**Comment by guochengqian** [comment]
At least we know that ResDeepGCN-28 can be trained on one V100 on partnet dataset where there are 10,000 points per frame.

**Comment by lightaime** [comment]
Hi @malcolmyanguci. You should be able to load your data on a NVIDIA V100 32G. However, I guess you need to set a small batch size. I advise you can also reduce the number of layers or the input resolution.

**Comment by MCLYang** [comment]
@guochengqian @lightaime Thank you for help. I reduced n_blocks down to 7 in opt file and it works now.
