### ISSUE TITLE
Different way of defining global pooling?

### ISSUE THREAD

**Issue by Hippogriff** [lightaime/deep_gcns_torch#24]
I have a rather conceptual question. I noticed that the global pooling in your code find max feature from the 1024 dim vector and this is concatenated with per point feature. In the older dynamic edge convolution network, the global pooling was done across all points giving 512 dim global vector which is concatenated with per point feature.

I am wondering why did you choose to do this? In my opinion 1 dim vector per point doesn't contain much information and I think it might not make any difference in the performance.

**Comment by lightaime** [comment]
Hi @Hippogriff. Could you kindly remind me which experiment you are looking at? For all the point clouds experiments, we concatenat the global feature with per point feature (see https://github.com/lightaime/deep_gcns_torch/blob/c1e43016b4ac6e29b0d6fa808c089739b773c89e/examples/sem_seg_dense/architecture.py#L56). But you are right for the PPI experiemnt, the 1 dim vector concatenation is unnecessary. You can remove it. Any we also find for the PPI experiment, global feature does not help. We remove it for the later follow-up work. However, we keep it for this version since we train the checkpoints of models for PPI with this implementation. To keep the results consistent, we left it as it.

**Comment by Hippogriff** [comment]
I am looking at this: https://github.com/lightaime/deep_gcns_torch/blob/master/examples/part_sem_seg/architecture.py#L64

I think the global information might not be very important in larger scenes because individual object in large scene can move independent of each other, hence there might be less correlation between objects.
However, in partnet dataset, I think global information can be helpful.

**Comment by lightaime** [comment]
Oh, You are right. It seems we didn't commit the new version of code for PartNet. I apologize for this. Actually, we did change the global pooling to be as the same that we use on S3DIS. And it is helpful for the performance. However, the PartNet experiment is for our [TPAMI submission](https://arxiv.org/abs/1910.06849), we are still working on the revision. We will update a new version of the preprint as well as the code as soon as possible. Thanks for pointing it out.

For your renference, I provide the results here. But please refer to our new comming preprint for the final results.
| bed  | bottle | chair | clock | dishw. | disp. | door | earph. | fauc. | knife | lamp | micro. | fridge | st. furn. | table | tr. can | vase |
|------|--------|-------|-------|--------|-------|------|--------|-------|-------|------|--------|--------|-----------|-------|---------|------|
| 35.9 | 49.3   | 41.1  | 33.8  | 56.2   | 81.0  | 31.1 | 45.8   | 52.8  | 44.5  | 23.1 | 51.8   | 34.9   | 47.2      | 33.6  | 50.8    | 54.2 |

**Comment by Hippogriff** [comment]
So in your new results for PartNet, is the global pooling layer same as other semantic segmentation architecture? Also, for reference, are the results posted above follows your ResGCN-28 setting?

I am investigating the role of different neighborhood of convolution in the initial layers of point based network and your codebase has been a huge help.

By the way, thanx a lot for providing the excellent code base and prompt replies to my queries.

**Comment by lightaime** [comment]
Yes, the results are obtained with the ResGCN-28 setting. The global pooling layer is the same as other semantic segmentation architecture. We will commit the code soon. But for now, you can refer to our implementation on S3DIS (https://github.com/lightaime/deep_gcns_torch/blob/master/examples/sem_seg_dense/architecture.py).

Glad to hear that our code is helpful. Good luck with your project!

**Comment by Hippogriff** [comment]
Thanx a lot!

**Comment by guochengqian** [comment]
Hi. @Hippogriff  Thanks for your interest in DeepGCNs. 
We have pushed the latest code for our partnet experiment. For feel to ask questions and make 
contributions.

**Comment by Hippogriff** [comment]
@guochengqian  Thank you.
