### ISSUE TITLE
Error when training sem_seg_sparse with dense block

### ISSUE THREAD

**Issue by mingloo** [lightaime/deep_gcns_torch#26]
When using below command for training sem_seg_sparse model

```
CUDA_VISIBLE_DEVICES=0,1 python examples/sem_seg_sparse/train.py  --multi_gpus --phase train --train_path data/S3DIS --block dense --conv mr --batch_size 16
```

The following error message will pop up:
```
RuntimeError: size mismatch, m1: [16384 x 128], m2: [256 x 64] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:290
```

I think it is because the `in_channels` of `DenseDynBlock` in the https://github.com/lightaime/deep_gcns_torch/blob/master/gcn_lib/sparse/torch_vertex.py#L186 is wrong? 

```
class DenseDynBlock(nn.Module):
    """
    Dense Dynamic graph convolution block
    """
    def __init__(self, channels,  kernel_size=9, dilation=1, conv='edge', act='relu', norm=None, bias=True, **kwargs):
        super(DenseDynBlock, self).__init__()
        self.body = DynConv(channels*2, channels, kernel_size, dilation, conv,
                            act, norm, bias, **kwargs)

    def forward(self, x, batch=None):
        dense = self.body(x, batch)
        return torch.cat((x, dense), 1), batch
```

@lightaime @guochengqian  Could you please help confirm the issue reported here?

**Comment by guochengqian** [comment]
Hello. For the sparse one, we only debug the resblock. We suggest everyone interested in semantic segmentation to use semsegdense instead. 
I will fix these issues in 5 hours and let you know.

**Comment by guochengqian** [comment]
@mingloo Hi. DenseGCN is available in sem_seg_dense and sem_seg_sparse Now!
Feel free to ask further questions. 
Please follow the new readme file for each experiment.

**Comment by mingloo** [comment]
@guochengqian  Thanks for your quick fix.
