### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by nanfangyinan1** [lightaime/deep_gcns_torch#27]
I hope to be able to obtain pre-trained network data for the experiment, I have submitted the application on Google Cloud Disk, my account is nanfangyinan@gamil.com.

**Comment by lightaime** [comment]
Hi @nanfangyinan1. Which is the experiment you asking?

**Comment by guochengqian** [comment]
Hello, thanks for your interest. We release the pre-trained models for PartNet experiments today. Please check the latest readme files for all the experiments.
