### ISSUE TITLE
ImportError: cannot import name 'scale_translate_pointcloud' from 'utils'

### ISSUE THREAD

**Issue by AshWYL** [lightaime/deep_gcns_torch#28]
When I try to run the train code of Part Segmentation on PartNet, I got this issue, can you help?

Traceback (most recent call last):
File "main.py", line 13, in
from utils import scale_translate_pointcloud
ImportError: cannot import name 'scale_translate_pointcloud' from 'utils' (/home/jrl/Github/deep_gcns_torch-master/examples/part_sem_seg/../../utils/init.py)

**Comment by guochengqian** [comment]
@AshWYL  Hi. Thanks for pointing it out and I feel sorry for my mistakenly deleting the required function somehow. Please pull the latest code. Also, the pre-trained models of PartNet are available.

**Comment by AshWYL** [comment]
Hi, Thanks! It's worked and got good results, Looking forward to your future work！
