### ISSUE TITLE
Code seems to miss the fusion block

### ISSUE THREAD

**Issue by sYeaLumin** [lightaime/deep_gcns_torch#3]
Thanks for the pytorch version! 
But the code seems to miss the fusion block.

pytorch version:
```python
        out = self.head(x, edge_index).unsqueeze(0)
        out = self.backbone(out, batch)[0]
        out = self.prediction(out.transpose(1, 0).contiguous().view(out.shape[1], -1))
```
tf version:
```python
    graphs = self.build_gcn_backbone_block(self.inputs,
                                           vertex_layer_builder,
                                           edge_layer_builder,
                                           num_layers,
                                           skip_connect)
    fusion = self.build_fusion_block(graphs, num_vertices)
    self.pred = self.build_mlp_pred_block(fusion, num_classes)
```

**Comment by guochengqian** [comment]
@sYeaLumin Yes. You are right. Sorry for not mentioning that in our readme file. We are working on a better vision of pytorch code, which we will make publically today.  However, the pretrained_model may not be available for a while.

**Comment by guochengqian** [comment]
The new code is available. I will close this issue. Feel free to reopen.

Related note:
I will add more examples later.
