### ISSUE TITLE
PPI data load has a problem

### ISSUE THREAD

**Issue by im-wll** [lightaime/deep_gcns_torch#7]
![$FVZL9EECMGE7R}CN(U`(O8](https://user-images.githubusercontent.com/33930824/68541326-08e17000-03d9-11ea-912f-6f8a196ff2f1.png)
when I run the ppi/main.py ,there is a problem about data load. how should I do?

**Comment by im-wll** [comment]
现在PPI数据可以正常加载，但是训练时又出现了一个段错误（核心已转移）。我的环境上装了pytorch1.2,以及torch_gemotric等一系列的包，但是cuda与pytorch不匹配，所以GPU无法使用。除了GPU无法使用外，其他的环境都已装好。我不知道出现这个段错误是不是跟环境有关

**Comment by im-wll** [comment]
现在PPI数据可以正常加载，但是训练时又出现了一个段错误（核心已转移）。我的环境上装了pytorch1.2,以及torch_gemotric等一系列的包，但是cuda与pytorch不匹配，所以GPU无法使用。除了GPU无法使用外，其他的环境都已装好。我不知道出现这个段错误是不是跟环境有关
![MH3UUK`%JKE2@OPF$~%VFC9](https://user-images.githubusercontent.com/33930824/68567226-75b94080-0493-11ea-8e0a-73039344155c.png)

**Comment by lightaime** [comment]
can you try to install the recommended env setup by
`source deepgcn_env_install.sh`
