### ISSUE TITLE
What is your version of PyTorch？1.2.0？or>=1.4.0

### ISSUE THREAD

**Issue by LCHJ** [lightaime/deep_gcns_torch#71]
Hello! I would like to know: What is your version of PyTorch？1.2.0？or>=1.4.0
Thank you !

**Comment by lightaime** [comment]
Hi @LCHJ. Pytorch >=1.4.0 should work fine.

**Comment by LCHJ** [comment]
Oh,I see.Thank you !&nbsp;&nbsp;
But your deepgcn.yml shows that is 1.2.0.



---Original---

**Comment by lightaime** [comment]
I see. Sorry for the confusion. You can installl the env using https://github.com/lightaime/deep_gcns_torch/blob/master/deepgcn_env_install.sh.

**Comment by LCHJ** [comment]
OKOK，Thanks for your contribution！



---Original---

**Comment by lightaime** [comment]
Great. I closed this issue. Feel free to reopen it if you have any problem.
