### ISSUE TITLE
error occurs in training modelnet40 after epoch 20  

### ISSUE THREAD

**Issue by amiltonwong** [lightaime/deep_gcns_torch#74]
Hi, @lightaime ,

I got the error `RuntimeError: CUDA error: device-side assert triggered`, after training modelnet40 in epoch 20 (details in [log.txt](https://gist.github.com/amiltonwong/40e4857800125135879033f2ac6486d5))

Could you give me some hints on how to fix this issue?

Thanks~

**Comment by guochengqian** [comment]
hi @amiltonwong  no worry, I will check it as soon as possible.

**Comment by guochengqian** [comment]
hi @amiltonwong. Please use the most recent code. I make the batch_index_select more stable. I train them just fine and easily reproduce the results.
