### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for DeepGCN during loading the pretrained model

### ISSUE THREAD

**Issue by amiltonwong** [lightaime/deep_gcns_torch#75]
Hi, @lightaime ,

When I perform the testing for modelnet40 using the pretrained model by command: 
```
python main.py --phase test --n_blocks 28 --block res  --pretrained_model ../../pretrained_models/modelnet_cls/ModelNet40-dense-edge-n14-C64-k9-drop0.5-lr0.001_B32_best_model.pth --data_dir /media/root/WDdata/dataset/modelnet40_dataset
```
I got the error: `RuntimeError: Error(s) in loading state_dict for DeepGCN:`
(details in [log.txt](https://gist.github.com/amiltonwong/4e1b779c657c410e3a6dc4fa1967b50d))

Any hints to solve this issue?

Thanks~

**Comment by lightaime** [comment]
Hi @amiltonwong. It seems you are loading a wrong model. You built a 28-layer model but loaded weights from a 14-layer checkpoint file.

**Comment by amiltonwong** [comment]
Thanks for notice:)
