### ISSUE TITLE
AttributeError: 'SummaryWriter' object has no attribute 'scalar_summary'

### ISSUE THREAD

**Issue by mtli77** [lightaime/deep_gcns_torch#77]
Hi @lightaime 

Thanks for sharing your code!
During the training stage on the ParNet dataset,  there is some bugs below:
```
Traceback (most recent call last):
  File "main.py", line 196, in <module>
    train(model, train_loader, val_loader, test_loader, opt)
  File "main.py", line 72, in train
    opt.writer.scalar_summary(tag, value, opt.step)
AttributeError: 'SummaryWriter' object has no attribute 'scalar_summary'
```
Could you help me to solve this problem? Does this a version confiliction?

**Comment by lightaime** [comment]
Hi @Violetit. It seems it is a problem with your tensorboard version. You can try to reinstall the latest version or comment out this line.

**Comment by mtli77** [comment]
> Hi @Violetit. It seems it is a problem with your tensorboard version. You can try to reinstall the latest version or comment out this line.

Hi @lightaime 
I commented this part of the code, and it works well now. 
thanks for your suggestion!
