### ISSUE TITLE
error when running visualize.py for part_sem_seg example

### ISSUE THREAD

**Issue by amiltonwong** [lightaime/deep_gcns_torch#78]
Hi, @lightaime ,

When I follow the [visualization step](https://github.com/lightaime/deep_gcns_torch/tree/master/examples/part_sem_seg#visualization), I can successfully run `step1` to generate *.obj.

`>> python eval.py --phase test --category 1 --pretrained_model /data/code13/deep_gcns_torch/pretrained_models/part_sem_seg/ResGCN-28/PartnetSemanticSeg-Bed-L3-res-edge-n28-C64-k9-drop0.5-lr0.005_B6-val_best_model.pth --data_dir /data/code13/deep_gcns_torch/partnet  --test_batch_size 4`

However, when I run `step2` (visualize.py) by this command:
`>> python visualize.py --category 1 --obj_no 0 --dir_path /data/code13/deep_gcns_torch/pretrained_models/part_sem_seg/ResGCN-28/result --folders res`, I got the following `IndexError` error:

```
Using vtk version 9.0.1
(2, 10000, 3)
0.0
0.5
Traceback (most recent call last):
  File "visualize.py", line 51, in <module>
    orientation='horizontal')
  File "/data/code13/deep_gcns_torch/utils/pc_viz.py", line 274, in visualize_part_seg
    orientation=orientation)
  File "/data/code13/deep_gcns_torch/utils/pc_viz.py", line 183, in show_pointclouds
    renderers[i].AddActor(ta)
IndexError: list index out of range

```

Any hints to solve this issue?

Thanks~

**Comment by guochengqian** [comment]
hi @amiltonwong , 
The original code only supports visualize three point clouds in the same time.  I just modified the code to make it support other cases (like only two point clouds in your case).

Your problem will not happen any more.  Look at the updated readme file for details.
