### ISSUE TITLE
Have you applied DeepGCNs to the classification of objects in ModelNet40？ 

### ISSUE THREAD

**Issue by linhaojia13** [lightaime/deep_gcns_torch#8]
I think this is a natural idea that could evaluate the capacity of learning feature by DeepGCNs, which is more convenient to conduct than evaluation on S3DIS.

**Comment by wsunid** [comment]
Good issue!  I am wondering too!

**Comment by guochengqian** [comment]
Thanks for your interest. We will update ModelNet classification in two weeks.

**Comment by linhaojia13** [comment]
I'm looking forward it!

**Comment by lightaime** [comment]
Hi @linhaojia13 @weiweisun2018. I would like to also point you to our new research [SGAS](https://github.com/lightaime/sgas/tree/master/gcn/gcn_point) where we show how to search SOTA GCN arhitectures automatically for ModelNet classification.

**Comment by lightaime** [comment]
Hi @linhaojia13 @weiweisun2018 . Our codes of for ModelNet40 classification is released. Please check: https://github.com/lightaime/deep_gcns_torch/tree/master/examples/modelnet_cls. Have fun!

**Comment by linhaojia13** [comment]
@lightaime Thank you very much! You are such a nice guy.
