### ISSUE TITLE
Not using edge features

### ISSUE THREAD

**Issue by mdanb** [lightaime/deep_gcns_torch#83]
I'd like to apply the ogbg ppa model on my own data. However, my data doesn't have edge features. Would I then just set `edge_attr = torch.zeros(edge_index.shape[1]).reshape(-1,1)` in the `forward` function (in model.py) before `edge_emb = self.edge_encoder(edge_attr)`? 

Thanks in advance!

**Comment by lightaime** [comment]
Hi @mdanb.  If you don't have edge features, you can just remove all the lines related to the edge features. You can also check the model of ogbn-arxiv which does not have edge features.
