### ISSUE TITLE
Would you consider providing codes based on `DGL`?

### ISSUE THREAD

**Issue by antecede** [lightaime/deep_gcns_torch#91]
Dear authors,

Would you consider providing codes based on `DGL`?

Thank you very much.

Best regards,
Bing
yangbingheart@163.com

**Comment by lightaime** [comment]
Hi @antecede, I found the DGL team provided an example of DeeperGCN: https://github.com/dmlc/dgl/blob/master/examples/README.md#deepergcn. We also provided an example of RevGNN with DGL implementation: https://github.com/lightaime/deep_gcns_torch/tree/master/examples/ogb_eff/ogbn_arxiv_dgl.

**Comment by antecede** [comment]
> Hi @antecede, I found the DGL team provided an example of DeeperGCN: https://github.com/dmlc/dgl/blob/master/examples/README.md#deepergcn. We also provided an example of RevGNN with DGL implementation: https://github.com/lightaime/deep_gcns_torch/tree/master/examples/ogb_eff/ogbn_arxiv_dgl.

Thank you for your prompt reply!  Awesome works!
