### ISSUE TITLE
AttributeError from 'torch_vertex.py'

### ISSUE THREAD

**Issue by psh9002** [lightaime/deep_gcns_torch#93]
When I execute `examples/ppi/main.py`, there was an attribute error from `/gcn_lib/sparse/torch_vertex.py`.
`AttributeError: module ‘torch_geometric.utils‘ has no attribute ‘scatter_‘`

The latest PyG doesn't have scatter_ at `torch_geometric.utils`
[https://pytorch-geometric.readthedocs.io/en/latest/modules/utils.html#](https://pytorch-geometric.readthedocs.io/en/latest/modules/utils.html#)

I resolve this issue by just adding `scatter_` mathod to `torch_vertex.py` from [previous version](https://pytorch-geometric.readthedocs.io/en/1.4.1/_modules/torch_geometric/utils/scatter.html#scatter_).

**Comment by lightaime** [comment]
Thanks, @psh9002 for your quick fix! I fixed this issue according to your suggestion.
